name: Github Actions Demo
run-name : ${{github.actor}} is testing out github actions
on : [push]

jobs:
  Explore-Github-Actions:
    runs-on: arch-linux
    steps:
      - run : echo "job was automatically triggered by {{github.event_name}} event"
      - run : echo "this job is running on ${{runner.os}} server hosted by Github"
      - run : echo  "name of the branch {{github.ref}}"
      - name : check out respository  code`
        uses : actions/checkout@v4
        -name : list all the files in the repo
      - run : |
        ls ${{github.workspace}}
      - run : echo "this job status is {{job.status}}"

